# Generated by Django 3.0.6 on 2021-05-09 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import project_app.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=9, validators=[project_app.validators.validate_phone], verbose_name='Telefon (+48...)')),
                ('status', models.SmallIntegerField(choices=[(1, 'Administrator'), (2, 'Rehabilitant'), (3, 'Pacjent')], verbose_name='Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('message', models.TextField(blank=True, verbose_name='Notatka')),
                ('patient', models.ForeignKey(limit_choices_to={'is_active': True, 'status': 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pacjent')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.SmallIntegerField(unique=True, verbose_name='Pokój')),
            ],
        ),
        migrations.CreateModel(
            name='UserUniqueToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_timetable', models.DateField(verbose_name='Dzień')),
                ('hour_timetable', models.SmallIntegerField(choices=[(1, '8:00 - 11:00'), (2, '11:00 - 14:00'), (3, '14:00 - 17:00')], verbose_name='Godzina')),
                ('employee', models.ForeignKey(limit_choices_to={'is_active': True, 'status': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_timetable', to=settings.AUTH_USER_MODEL, verbose_name='Rehabilitant')),
                ('patient', models.ForeignKey(limit_choices_to={'is_active': True, 'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_timetable', to=settings.AUTH_USER_MODEL, verbose_name='Pacjent')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Reservation', verbose_name='Rezerwacja')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.Room', verbose_name='Pokój'),
        ),
    ]
