# Generated by Django 3.0.6 on 2021-01-19 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_timetable', models.DateField()),
                ('hour_timetable', models.SmallIntegerField(choices=[(1, '8:00 - 11:00'), (2, '11:00 - 14:00'), (3, '14:00 - 17:00')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_timetable', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_timetable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day_timetable', 'hour_timetable')},
            },
        ),
    ]
