# Generated by Django 3.0.6 on 2021-01-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
    ]
