# Generated by Django 3.0.6 on 2021-04-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20210425_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='during_reservation',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_reservation',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_reservation',
            new_name='start_date',
        ),
    ]
