# Generated by Django 3.0.6 on 2021-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210425_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, verbose_name='Notatka'),
        ),
    ]
