# Generated by Django 3.0.6 on 2021-01-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_auto_20210124_1450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day_timetable', 'patient')},
        ),
    ]
