# Generated by Django 3.0.6 on 2021-01-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20210124_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.Reservation'),
        ),
    ]
