# Generated by Django 3.0.6 on 2021-05-01 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_auto_20210501_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_timetable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_timetable', to=settings.AUTH_USER_MODEL),
        ),
    ]
